name: flutter_azimuth_example
description: Demonstrates how to use the flutter_azimuth plugin.

publish_to: none

version: 3.38.9+1

environment:
    sdk: ^3.10.8

dependencies:
    flutter:
        sdk: flutter

    flutter_azimuth:
        path: ../

    cupertino_icons: ^1.0.8
    google_fonts: ^8.0.2
    haptic_feedback: ^0.6.4+3
    console_tools: ^1.0.1
    audioplayers: ^6.5.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    flutter_native_splash: ^2.4.7
    flutter_launcher_icons: ^0.14.4
    path: ^1.9.1


flutter:
    uses-material-design: true

    assets:
        - assets/
    fonts:
        - family: Digital
          fonts:
              - asset: assets/digital7/digital7.ttf
              - asset: assets/digital7/italic.ttf
              - asset: assets/digital7/mono.ttf
              - asset: assets/digital7/mono_italic.ttf
