name: flutter_azimuth
description: A Flutter Compass Tools Implementation, is the plugin that measure The Azimuth is the angle between magnetic north, and the the orientatin of the device.

version: 3.10.8

homepage: https://github.com/ymrabti
environment:
  sdk: ^3.10.8
  flutter: ">=1.10.0"  

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ymrabtipacks.flutter_azimuth
        pluginClass: FlutterAzimuthPlugin
      ios:
        pluginClass: FlutterAzimuthPlugin
